### ISSUE TITLE
Address complexity introduced by getTomatoLink

### ISSUE THREAD

**Issue by gabrielweyer** [joshblum/netflix-rate-chrome-ext#11]
Currently we're doing nested functions calls (`getRating` and then `getTomatoLink`) in order to retrieve everything we need to display the ratings.

This is due to the fact that a new field was introduced in the cache (`tomatoAliasUrl`). The easiest way to deal with this would be to version the cache.

The key would be composed of the Netflix Id and the cache version (for example `media_1_70251894`). This way when we add something new to the cache we don't need to add any logic, the key would become `media_2_70251894` and everything would be retrieved again. Of course it means more API calls when we change the version of the cache.

**Comment by joshblum** [comment]
Versioning sounds good. It might make more sense to add a version field so the cache won't be filled with old invalid entries and leave the key as being the title. Thus when we check the cache we just check that the version key matches the global key and that the date field has not expired.

Do you want to implement this? Also, do you have experience with firefox extensions? These fixes can also apply to the [FF version](https://github.com/joshblum/netflix-rate-firefox-ext)

**Comment by gabrielweyer** [comment]
I'll have a look next weekend, it shouldn't be too hard.

In fact I didn't have experience with Chrome extensions before submitting my first PR request here :smile: I'll see if the fixes are easy to port.

**Comment by joshblum** [comment]
Ok sweet if I have time this week I can also take a look so we'll see who has time first :p

I ported your first set of fixes already -- ideally I should just merge the two repos and have a build script that makes the respective extensions since they are almost identical except a few api differences.
