### ISSUE TITLE
Rotten Tomatoes deprecated the alias page

### ISSUE THREAD

**Issue by gabrielweyer** [joshblum/netflix-rate-chrome-ext#9]
The links going to Rotten Tomatoes end up being a 404.

Rotten Tomatoes does not support the alias anymore as explained [here](http://developer.rottentomatoes.com/forum/read/110751/2).

Maybe we could leverage something like [this](http://developer.rottentomatoes.com/docs/read/json/v10/Movie_Alias) instead.

**Comment by joshblum** [comment]
@gabrielweyer great call. I wasn't aware that the API became depreciated I'll look into implementing this in addition to #8. Thank you so much for contributing!
